"""Disposition-stock rebound — long the name once it enters TWSE/TPEx disposition.

Self-contained per strategy-import-spec v1 §3 rule 10: no imports from
``_common`` or sibling bundles. Event dates come from the bundle-local
``assets/events.csv``, regenerated by ``scripts/export_disposition_events.py``.

The trade
---------
A Taiwan stock that trips the TWSE/TPEx surveillance thresholds is placed under
"disposition" (處置): trading moves from continuous matching to a periodic call
auction (5-minute for a first offence, 20-minute for a repeat), intraday day
trading is banned, and repeat offenders additionally require pre-payment of
cash and stock. The folk trade is to short it on day one. Measured on 2,101
episodes from 2021-01 to 2026-08, that is wrong twice over:

  * shorting is mechanically unavailable -- 100% of disposition stock-days also
    carry the day-trade ban, and margin short-sell volume collapses to a median
    of ~5 lots/day, which is not capacity, it is a rounding error;
  * the entry-day drop is only about -64 bps against a matched control, less
    than the ~111 bps it costs to round-trip a short.

What the data does support is the opposite side: sessions +1..+10 after entry
earn a *positive* abnormal return. Against a momentum- and turnover-matched
control basket the effect is roughly +340 bps gross per episode; unhedged and
after ~91 bps of costs it is about +278 bps per trade (t = 7.5), positive in
five of six calendar years.

Honest limits, restated here because they belong next to the code:
  * capacity. Traded value during the holding window is a fraction of normal,
    and fills happen in a 5- or 20-minute call auction, not on a continuous
    book. Position sizing must be tied to *during-disposition* volume, which is
    unknown at entry.
  * the edge dies somewhere around 400 bps of round-trip cost. That is real
    headroom, but call-auction slippage on an illiquid name is genuinely
    uncertain and could plausibly reach it.
  * 2022 -- the one bear-market year in the sample -- was flat (-7 bps, t=-0.05).

See docs/math-spec-pv-technical-analysis.md §9 and
docs/findings-disposition-rebound.md for the full study.
"""
import os

import pandas as pd

from zipline.api import order_target_percent, record, symbol

#: Columns in assets/events.csv that describe how the episode ACTUALLY ended.
#: They are diagnostics. Reading them at entry time is look-ahead, so this
#: module never touches them and the name is kept explicit as a tripwire.
_FUTURE_COLUMNS = ("realised_end", "realised_sessions")


def load_events(context):
    """Read the sidecar event calendar, keeping only ex-ante columns."""
    path = os.path.join(os.path.dirname(__file__), context.events_csv)
    df = pd.read_csv(path, parse_dates=["date"])
    df = df.drop(columns=[c for c in _FUTURE_COLUMNS if c in df.columns])

    if context.min_strength is not None and "strength" in df.columns:
        # NaN strength means the pre-event momentum was unavailable (e.g. the
        # first session in the sample). Dropping those silently would quietly
        # shrink the universe, so it is done explicitly and recorded.
        df = df[df["strength"].notna() & (df["strength"] >= context.min_strength)]

    if context.auction_interval_min is not None and "auction_interval_min" in df.columns:
        df = df[df["auction_interval_min"] == context.auction_interval_min]

    return df.sort_values("date").reset_index(drop=True)


def initialize(context):
    p = getattr(context, "params", {}) or {}
    context.events_csv = p.get("events_csv", "assets/events.csv")
    context.hold_sessions = int(p.get("hold_sessions", 10))
    context.position_pct = float(p.get("position_pct", 0.04))
    context.max_concurrent = int(p.get("max_concurrent", 12))
    # None = take every episode. Set a float to require a minimum pre-event
    # 20-day run-up; set 5 or 20 to trade only first / repeat dispositions.
    context.min_strength = p.get("min_strength", None)
    context.auction_interval_min = p.get("auction_interval_min", None)

    context.events = load_events(context)
    context.events_by_day = {
        d.normalize(): g for d, g in context.events.groupby("date")
    }
    context.holdings = {}      # asset -> sessions remaining
    context.skipped_unknown = 0
    context.skipped_capacity = 0


def handle_data(context, data):
    today = context.get_datetime().tz_localize(None).normalize()

    # 1) age existing positions first, so a slot freed today can be reused today
    for asset in list(context.holdings):
        context.holdings[asset] -= 1
        if context.holdings[asset] <= 0:
            order_target_percent(asset, 0)
            del context.holdings[asset]

    # 2) open new positions for episodes starting today
    due = context.events_by_day.get(today)
    if due is not None:
        for _, row in due.iterrows():
            if len(context.holdings) >= context.max_concurrent:
                context.skipped_capacity += 1
                continue
            try:
                asset = symbol(str(row["symbol"]))
            except Exception:
                # Not every disposition name is in the equity bundle (warrants,
                # foreign-registered shares, names delisted before ingestion).
                # Counted rather than swallowed: a silent drop here would
                # quietly turn a survivorship problem into a clean-looking one.
                context.skipped_unknown += 1
                continue
            if asset in context.holdings:
                continue
            if not data.can_trade(asset):
                context.skipped_capacity += 1
                continue
            order_target_percent(asset, context.position_pct)
            context.holdings[asset] = context.hold_sessions

    record(
        n_positions=len(context.holdings),
        skipped_unknown=context.skipped_unknown,
        skipped_capacity=context.skipped_capacity,
    )
